export const UPDATE_ONBOARDING_STATUS = 'UPDATE_ONBOARDING_STATUS';
export const UPDATE_USER_AUTH_DETAILS = 'UPDATE_USER_AUTH_DETAILS';
export const UPDATE_USER_LOGIN = 'UPDATE_USER_LOGIN';
export const UPDATE_LOGGED_IN_STATUS = 'UPDATE_LOGGED_IN_STATUS';
export const UPDATE_USER_ACCESS_TOKEN = 'UPDATE_USER_ACCESS_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';

// QUIZ
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_TEST = 'UPDATE_TEST';
export const CLEAR_TEST = 'CLEAR_TEST';
export const UPDATE_SELECTED_OPTIONS = 'UPDATE_SELECTED_OPTIONS';
export const UPDATE_CORRECTION = 'UPDATE_CORRECTION';
export const CLEAR_CORRECTION = 'CLEAR_CORRECTION';


// TESTS
export const TEST_DATA = "TEST_DATA";
export const PAST_QUESTIONS = "PAST_QUESTIONS";
export const UPDATE_CHANNEL_ID = "UPDATE_CHANNEL_ID";
export const UPDATE_CHANNEL_ID2 = "UPDATE_CHANNEL_ID2";
export const UPDATE_COURSE_DETAIL = "UPDATE_COURSE_DETAIL";
export const UPDATE_LEADERBOARD = "UPDATE_LEADERBOARD";